### ISSUE TITLE
Add a command to create release tarballs (with modules included in "vendor" directory)

### ISSUE THREAD

**Issue by CyberTailor** [diamondburned/gotk4-nix#1]
This would aid packaging efforts.

**Comment by diamondburned** [comment]
I'm confused how this would help packaging efforts. Does `buildGoModule` not work? Or is this for build caching?

**Comment by CyberTailor** [comment]
This is for source tarballs with dependencies included

**Comment by diamondburned** [comment]
Added in https://github.com/diamondburned/gotk4-nix/commit/9bb4e047baa4f99804c238a209ecf13273dab384.
